package com.zorva.gigshield.ui.legal

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.zorva.gigshield.databinding.ActivityLegalBinding

/**
 * Legal Shield — appeal generator and rights guide for gig workers.
 *
 * Features:
 * - Generate appeal letters for unfair deactivation
 * - Know Your Rights guide with gig worker laws
 * - Access to government scheme eligibility checker
 */
class LegalShieldActivity : AppCompatActivity() {

    private lateinit var binding: ActivityLegalBinding

    // ── Rights information ───────────────────────────────────
    private val rightsInfo = listOf(
        RightItem(
            "Code on Social Security, 2020",
            "Gig workers are now covered under social security legislation. " +
            "You are entitled to life & disability cover, health benefits, " +
            "maternity benefits, and old age protection.",
            "Central Government"
        ),
        RightItem(
            "Right to Fair Termination",
            "Platforms cannot deactivate your account without prior notice and " +
            "valid reason. You have the right to appeal any deactivation within 30 days.",
            "Social Security Code, Section 114"
        ),
        RightItem(
            "eShram Registration",
            "Register on eShram portal (eshram.gov.in) to get a unique UAN number. " +
            "This provides ₹2 lakh accidental insurance and access to welfare schemes.",
            "Ministry of Labour"
        ),
        RightItem(
            "Right to Grievance Redressal",
            "File complaints against platforms with the Labour Commissioner. " +
            "Platforms are mandated to have internal grievance mechanisms.",
            "Industrial Disputes Act"
        ),
        RightItem(
            "Minimum Wage Protection (Evolving)",
            "Several states are pushing for minimum wage guarantees for gig workers. " +
            "Rajasthan passed the Gig Workers Act 2023 mandating a welfare fund.",
            "State Labour Laws"
        ),
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityLegalBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setupUI()
    }

    private fun setupUI() {
        // Appeal generator
        binding.btnGenerateAppeal.setOnClickListener {
            val platform = binding.etPlatform.text.toString().ifBlank { "the platform" }
            val reason = binding.etDeactivationReason.text.toString().ifBlank { "No reason provided by platform" }
            val workerId = binding.etWorkerId.text.toString().ifBlank { "Not specified" }

            val appeal = generateAppealLetter(platform, reason, workerId)
            binding.tvAppealOutput.text = appeal
        }

        // Rights list
        val rightsText = rightsInfo.joinToString("\n\n") { right ->
            "⚖️ ${right.title}\n${right.description}\n📌 Source: ${right.source}"
        }
        binding.tvRightsGuide.text = rightsText

        binding.btnBack.setOnClickListener { finish() }
    }

    private fun generateAppealLetter(
        platform: String,
        reason: String,
        workerId: String
    ): String {
        return """
To,
The Grievance Officer
$platform

Subject: Appeal Against Unfair Deactivation of Account

Respected Sir/Madam,

I am writing to formally appeal the deactivation of my account (Worker ID: $workerId) on your platform.

Reason cited for deactivation: $reason

I believe this action is unjustified and request an immediate review based on the following grounds:

1. I have maintained a consistent work record and positive customer ratings throughout my tenure on the platform.

2. Under the Code on Social Security, 2020, gig workers are entitled to fair treatment and due process before termination of platform access.

3. No prior warning or opportunity to respond was provided before the deactivation, which violates natural justice principles.

I request that my account be reactivated forthwith, or that a detailed explanation with supporting evidence be provided for the deactivation decision.

I reserve my right to escalate this matter to the Labour Commissioner and relevant authorities if a satisfactory resolution is not provided within 15 working days.

Thanking you,

[Your Name]
[Your Phone Number]
[Your City]
Date: ${java.time.LocalDate.now()}

---
This letter was generated by Zorva GigShield Legal Aid.
Reference: Code on Social Security 2020, Sec. 114
        """.trimIndent()
    }

    data class RightItem(
        val title: String,
        val description: String,
        val source: String
    )
}
